/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptrinhjava_doan;

import Component.CardView;
import Component.WrapLayout;
import Model.Model_card;
import Model.generateRandomString;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class DanhMucThietBi extends javax.swing.JFrame {

    /**
     * Creates new form DanhMucThietBi
     */
    int soluong=0;
    double giatien;
    String IDThietBi="";
    public DanhMucThietBi() {
        initComponents();
        setResizable(false);
        init();
    }
    private void init(){
        ArrayList<CardView> lstCardView=new ArrayList<>();
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="select * from ltjava_doan.thietbi";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next())
            {
                Model_card cv=new Model_card();
                cv.setId(rs.getString("IDThietBi"));
                cv.setTitle(rs.getString("TenThietBi"));
                cv.setDescription(String.valueOf(rs.getDouble("DonGia")));
                cv.setSoluong(rs.getInt("SoLuong"));
                byte[]imageData=rs.getBytes("imageTB");
                if(imageData!=null)
                {
                    InputStream in=new ByteArrayInputStream(imageData);
                    BufferedImage image=ImageIO.read(in);
                    cv.setIcon(new ImageIcon(image));
                }
                lstCardView.add(new CardView(cv));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(jPanel2, "Error"+e);
        }
        jPanel2.setLayout(new WrapLayout(WrapLayout.LEADING));
        jScrollPane1.setVerticalScrollBar(new JScrollBar());
        for(CardView item : lstCardView)
        {
            jPanel2.add(item);
            item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDThietBi=item.db.getId();
                String title=item.db.getTitle();
                String dongia=item.db.getDescription();
                giatien=Double.parseDouble(dongia);
                soluong=item.db.getSoluong();
                tfshowTenThietBi.setText(title);
                tfshowSoLuong.setText("1");
                tfshowThanhTien.setText(dongia);
            }
            });
        }
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfshowSoLuong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfshowTenThietBi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfshowThanhTien = new javax.swing.JTextField();
        btnThemGioHang = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListThietBi = new javax.swing.JTable();
        tfDeleteTB = new javax.swing.JTextField();
        btnDeleteTB = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 244, 239));

        jPanel1.setBackground(new java.awt.Color(248, 244, 239));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Tên Thiết bị:");

        tfshowSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfshowSoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("Số lượng");

        tfshowTenThietBi.setEditable(false);
        tfshowTenThietBi.setBackground(new java.awt.Color(255, 255, 255));
        tfshowTenThietBi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfshowTenThietBi.setText(" ");
        tfshowTenThietBi.setToolTipText("");
        tfshowTenThietBi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Thành tiền:");

        tfshowThanhTien.setEditable(false);
        tfshowThanhTien.setBackground(new java.awt.Color(255, 255, 255));
        tfshowThanhTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfshowThanhTien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnThemGioHang.setBackground(new java.awt.Color(153, 204, 255));
        btnThemGioHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemGioHang.setForeground(new java.awt.Color(255, 255, 255));
        btnThemGioHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cart-30.png"))); // NOI18N
        btnThemGioHang.setText("Thêm vào giỏ hàng");
        btnThemGioHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnThemGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGioHangActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 102));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-32.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-minus-32.png"))); // NOI18N
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(153, 204, 255));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-payment-30.png"))); // NOI18N
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        tbListThietBi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tbListThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbListThietBi.setRowHeight(30);
        jScrollPane2.setViewportView(tbListThietBi);

        tfDeleteTB.setBackground(new java.awt.Color(255, 153, 153));
        tfDeleteTB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfDeleteTB.setText("Nhập vị trí muốn xóa");
        tfDeleteTB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tfDeleteTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfDeleteTBMouseClicked(evt);
            }
        });
        tfDeleteTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDeleteTBActionPerformed(evt);
            }
        });

        btnDeleteTB.setBackground(new java.awt.Color(204, 255, 204));
        btnDeleteTB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnDeleteTB.setText("Xóa");
        btnDeleteTB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnDeleteTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfshowTenThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfshowThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnMinus)
                                                .addGap(18, 18, 18)
                                                .addComponent(tfshowSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAdd))
                                            .addComponent(btnThemGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfDeleteTB, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDeleteTB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 26, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfshowSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfshowTenThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(btnMinus))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfshowThanhTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(btnThemGioHang)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThanhToan)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(tfDeleteTB))
                                    .addComponent(btnDeleteTB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int sl=Integer.parseInt(tfshowSoLuong.getText().toString());
        if(sl>=soluong)
        {
            JOptionPane.showMessageDialog(rootPane, "Số lượng phải bé hơn số lượng tồn của thiết bị");
        }
        else
        {
            sl++;
            tfshowSoLuong.setText(String.valueOf(sl));
            double thanhtien=giatien*sl;
            tfshowThanhTien.setText(String.valueOf(thanhtien));
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        // TODO add your handling code here:
        int sl=Integer.parseInt(tfshowSoLuong.getText().toString());
        if(sl>1)
        {
            sl--;
            tfshowSoLuong.setText(String.valueOf(sl));
            double thanhtien=giatien*sl;
            tfshowThanhTien.setText(String.valueOf(thanhtien));
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnThemGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGioHangActionPerformed
        // TODO add your handling code here:
        String tentb=String.valueOf(tfshowTenThietBi.getText());
        if(tentb.contentEquals(" "))
        {
            JOptionPane.showMessageDialog(rootPane, "Không có thiết bị nào được thêm vào giỏ hàng");
        }
        else
        {
            DefaultTableModel model=(DefaultTableModel)tbListThietBi.getModel();
            Vector v=new Vector();
            v.add(model.getRowCount()+1);
            v.add(tfshowTenThietBi.getText());
            v.add(Integer.parseInt(tfshowSoLuong.getText()));
            v.add(Double.parseDouble(tfshowThanhTien.getText()));
            model.addRow(v);
        }
    }//GEN-LAST:event_btnThemGioHangActionPerformed

    private void tfDeleteTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDeleteTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDeleteTBActionPerformed

    private void tfDeleteTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfDeleteTBMouseClicked
        // TODO add your handling code here:
        tfDeleteTB.setText("");
    }//GEN-LAST:event_tfDeleteTBMouseClicked

    private void btnDeleteTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTBActionPerformed
        // TODO add your handling code here:
        if(tfDeleteTB.getText().contentEquals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Số thứ tự thiết bị không hợp lệ");
        }
        else
        {
            int stt=Integer.parseInt(tfDeleteTB.getText());
            DefaultTableModel model=(DefaultTableModel)tbListThietBi.getModel();
            int sttEnd=model.getRowCount();
            if(stt>sttEnd||stt<1)
            {
                JOptionPane.showMessageDialog(rootPane, "Số thứ tự không hợp lệ");
            }
            else{
                model.removeRow(stt-1);
                for(int i=0;i<sttEnd-1;i++)
                {
                    model.setValueAt(i+1, i, 0);
                }
            }
        }
    }//GEN-LAST:event_btnDeleteTBActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        int tongsl=0;
        double tongtien=0;
        DefaultTableModel model=(DefaultTableModel)tbListThietBi.getModel();
        for(int i=0;i<model.getRowCount();i++)
        {
            tongsl=tongsl+Integer.parseInt(model.getValueAt(i, 2).toString());
            tongtien=tongtien+Double.parseDouble(model.getValueAt(i, 3).toString());
        }
        String idHD="HD"+new generateRandomString().generateRandomString(2);
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        String addHD="insert into ltjava_doan.hoadon values (?,NULL,?,?,?)";
        try
        {
            ps=con.getConnection().prepareStatement(addHD);
            ps.setString(1, idHD);
            ps.setDate(2, new java.sql.Date(new Date().getTime()));
            ps.setInt(3,tongsl);
            ps.setDouble(4, tongtien);
            ps.executeUpdate();
            addToCTHD(idHD);
            removeAllRow();
            JOptionPane.showMessageDialog(rootPane, "Thêm hóa đơn thành công");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
        
    }//GEN-LAST:event_btnThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMucThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMucThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMucThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMucThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhMucThietBi().setVisible(true);
            }
        });
    }
    
    public void addToCTHD(String idhd)
    {
        ResultSet rs;
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        String query="insert into ltjava_doan.chitiethoadon values (?,?,?,?)";
        DefaultTableModel model=(DefaultTableModel)tbListThietBi.getModel();
        for(int i=0;i<model.getRowCount();i++)
        {
            try
            {
                String idsp="";
                String query1="select * from ltjava_doan.thietbi where TenThietBi=?";
                ps=con.getConnection().prepareStatement(query1);
                ps.setString(1,model.getValueAt(i, 1).toString());
                rs=ps.executeQuery();
                if(rs.next())
                {
                    idsp=rs.getString("IDThietBi");
                }
                ps=con.getConnection().prepareStatement(query);
                ps.setString(1, idhd);
                ps.setString(2,idsp);
                ps.setInt(3,Integer.parseInt(model.getValueAt(i, 2).toString()));
                ps.setDouble(4,Double.parseDouble(model.getValueAt(i, 3).toString()));
                ps.executeUpdate();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Error"+e);
            }
        }
    }
    
    public void removeAllRow()
    {
        DefaultTableModel model=(DefaultTableModel)tbListThietBi.getModel();
        model.setRowCount(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteTB;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemGioHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbListThietBi;
    private javax.swing.JTextField tfDeleteTB;
    private javax.swing.JTextField tfshowSoLuong;
    private javax.swing.JTextField tfshowTenThietBi;
    private javax.swing.JTextField tfshowThanhTien;
    // End of variables declaration//GEN-END:variables
}
