/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laptrinhjava_doan;

import Model.BanHD;
import Model.NHANVIEN;
import action.TableActionCellEditor;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.Cursor;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.Vector;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import action.TableActionCellRender;
import action.TableActionEvent;
import action.viewActionCellEditor;
import action.viewCellRender;
import action.viewEvent;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author TIEN THANH
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinCaNhan
     */
    String IDNV="";
    byte[] imageAvatar=null;
    
    public TrangChu(NHANVIEN nv) {
        initComponents();
        IDNV=nv.idnv;
        tvUserName.setText(nv.hoten);
        tvSex.setText(nv.gioitinh);
        tvDOB.setText(nv.ngaysinh.toString());
        tvAddress.setText(nv.diachi);
        tvSDT.setText(nv.sdt);
        showAvatar();
        showLoaiThietBi();
        showThietBi();
        showHoaDon();
        showPieChart();
    }
    public TrangChu()
    {
        initComponents();
        showLoaiThietBi();
        showThietBi();
        showHoaDon();
        showPieChart();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogChangePass = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfOldPass = new javax.swing.JPasswordField();
        jLabel19 = new javax.swing.JLabel();
        tfNewPass = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        tfConfirmNewPass = new javax.swing.JPasswordField();
        btnConfirmPass = new javax.swing.JButton();
        dialogChangeInfo = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnConfirmChangeInfo = new javax.swing.JButton();
        tfChangeUserName = new javax.swing.JTextField();
        tfChangeDIaChi = new javax.swing.JTextField();
        tfChangeSDT = new javax.swing.JTextField();
        btnNam = new javax.swing.JRadioButton();
        btnNu = new javax.swing.JRadioButton();
        btnGroupSex = new javax.swing.ButtonGroup();
        dialogshowCTHD = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCTHD = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnLoaiThietBi = new javax.swing.JButton();
        btnDMThietBi = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnTTTaiKhoan = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnLoaiThietBi1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        TabPane = new javax.swing.JTabbedPane();
        tabttTaiKhoan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tvAvatar = new javax.swing.JLabel();
        btnUpdateAvatar = new javax.swing.JButton();
        btnchangeUserInfo = new javax.swing.JButton();
        btnChangPass = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tvUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tvSex = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tvDOB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tvAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tvSDT = new javax.swing.JTextField();
        tabLoaiTB = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLoaiTB = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfMaLoai = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfTenLoai = new javax.swing.JTextField();
        btnAddLoaiTB = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tabDMTB = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbThietBi = new javax.swing.JTable();
        tfFindTB = new javax.swing.JTextField();
        btnFindTB = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnAddTB = new javax.swing.JButton();
        tfIDThietBi = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbIDLoai = new javax.swing.JComboBox<>();
        tfTenThietBi = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfDonGia = new javax.swing.JTextField();
        btnImageThietBi = new javax.swing.JButton();
        tfImageThietBi = new javax.swing.JTextField();
        tabHD = new javax.swing.JPanel();
        btnThemHD = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        panelThongKe = new javax.swing.JPanel();
        pieChartPanel = new javax.swing.JPanel();

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("ĐỔI MẬT KHẨU");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel15.setText("Mật khẩu cũ");

        tfOldPass.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfOldPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel19.setText("Mật khẩu mới");

        tfNewPass.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfNewPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel20.setText("Nhập lại mật khẩu mới");

        tfConfirmNewPass.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfConfirmNewPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnConfirmPass.setBackground(new java.awt.Color(153, 204, 255));
        btnConfirmPass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmPass.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmPass.setText("Xác nhận");
        btnConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogChangePassLayout = new javax.swing.GroupLayout(dialogChangePass.getContentPane());
        dialogChangePass.getContentPane().setLayout(dialogChangePassLayout);
        dialogChangePassLayout.setHorizontalGroup(
            dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChangePassLayout.createSequentialGroup()
                .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogChangePassLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dialogChangePassLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(tfConfirmNewPass))
                            .addGroup(dialogChangePassLayout.createSequentialGroup()
                                .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfOldPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(dialogChangePassLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel10))
                    .addGroup(dialogChangePassLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnConfirmPass)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        dialogChangePassLayout.setVerticalGroup(
            dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChangePassLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(dialogChangePassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfConfirmNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmPass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel21.setText("CHỈNH SỬA THÔNG TIN TÀI KHOẢN");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel22.setText("Họ tên");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel23.setText("Giới tính");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel25.setText("Địa chỉ");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel26.setText("Số điện thoại");

        btnConfirmChangeInfo.setBackground(new java.awt.Color(153, 204, 255));
        btnConfirmChangeInfo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmChangeInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmChangeInfo.setText("Xác nhận");
        btnConfirmChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmChangeInfoActionPerformed(evt);
            }
        });

        tfChangeUserName.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfChangeUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        tfChangeDIaChi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfChangeDIaChi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        tfChangeSDT.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfChangeSDT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnGroupSex.add(btnNam);
        btnNam.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnNam.setText("Nam");

        btnGroupSex.add(btnNu);
        btnNu.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnNu.setText("Nữ");

        javax.swing.GroupLayout dialogChangeInfoLayout = new javax.swing.GroupLayout(dialogChangeInfo.getContentPane());
        dialogChangeInfo.getContentPane().setLayout(dialogChangeInfoLayout);
        dialogChangeInfoLayout.setHorizontalGroup(
            dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChangeInfoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(dialogChangeInfoLayout.createSequentialGroup()
                        .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(53, 53, 53)
                        .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfChangeUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                            .addComponent(tfChangeDIaChi)
                            .addComponent(tfChangeSDT)
                            .addGroup(dialogChangeInfoLayout.createSequentialGroup()
                                .addComponent(btnNam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(dialogChangeInfoLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnConfirmChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogChangeInfoLayout.setVerticalGroup(
            dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogChangeInfoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel21)
                .addGap(36, 36, 36)
                .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(tfChangeUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(btnNam)
                    .addComponent(btnNu))
                .addGap(29, 29, 29)
                .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfChangeDIaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(dialogChangeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tfChangeSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tbCTHD.setBackground(new java.awt.Color(153, 204, 255));
        tbCTHD.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tbCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Hóa đơn", "ID Sản phẩm", "Số lượng", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCTHD.setGridColor(new java.awt.Color(102, 102, 102));
        tbCTHD.setRowHeight(30);
        tbCTHD.setSelectionBackground(new java.awt.Color(248, 244, 239));
        jScrollPane4.setViewportView(tbCTHD);

        javax.swing.GroupLayout dialogshowCTHDLayout = new javax.swing.GroupLayout(dialogshowCTHD.getContentPane());
        dialogshowCTHD.getContentPane().setLayout(dialogshowCTHDLayout);
        dialogshowCTHDLayout.setHorizontalGroup(
            dialogshowCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        dialogshowCTHDLayout.setVerticalGroup(
            dialogshowCTHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1015, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLoaiThietBi.setBackground(new java.awt.Color(204, 204, 204));
        btnLoaiThietBi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLoaiThietBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-supplier-32.png"))); // NOI18N
        btnLoaiThietBi.setText("<html><div style='text-align: center;'>Loại TB</div></html>");
        btnLoaiThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiThietBiActionPerformed(evt);
            }
        });

        btnDMThietBi.setBackground(new java.awt.Color(204, 204, 204));
        btnDMThietBi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDMThietBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-syringe-with-a-drop-of-blood-32.png"))); // NOI18N
        btnDMThietBi.setText("<html><div style='text-align: center;cursor:pointer'>Danh mục thiết bị</div></html>");
        btnDMThietBi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDMThietBiMouseReleased(evt);
            }
        });
        btnDMThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMThietBiActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        btnHoaDon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-invoice-32.png"))); // NOI18N
        btnHoaDon.setLabel("<html><div style='text-align: center;'>Hoá Đơn</div></html>");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnTTTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        btnTTTaiKhoan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnTTTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-user-menu-male-32.png"))); // NOI18N
        btnTTTaiKhoan.setText("<html><div style='text-align: center;'>Profile</div></html>");
        btnTTTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTTaiKhoanActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(204, 204, 204));
        btnLogOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-logout-32.png"))); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnLoaiThietBi1.setBackground(new java.awt.Color(204, 204, 204));
        btnLoaiThietBi1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLoaiThietBi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-analytics-32.png"))); // NOI18N
        btnLoaiThietBi1.setText("<html><div style='text-align: center;'>Thống kê</div></html>");
        btnLoaiThietBi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiThietBi1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Danh mục");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoaiThietBi1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(btnLoaiThietBi)
                    .addComponent(btnHoaDon)
                    .addComponent(btnTTTaiKhoan)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDMThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDMThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoaiThietBi1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoaiThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTTTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 627));

        tabttTaiKhoan.setBackground(new java.awt.Color(248, 244, 239));

        jPanel2.setBackground(new java.awt.Color(248, 244, 239));

        tvAvatar.setText("image");
        tvAvatar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpdateAvatar.setBackground(new java.awt.Color(126, 170, 146));
        btnUpdateAvatar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnUpdateAvatar.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateAvatar.setText("Đổi ảnh đại diện");
        btnUpdateAvatar.setBorder(null);
        btnUpdateAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateAvatarActionPerformed(evt);
            }
        });

        btnchangeUserInfo.setBackground(new java.awt.Color(84, 91, 119));
        btnchangeUserInfo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnchangeUserInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnchangeUserInfo.setText("<html><div style=\"word-wrap: break-word;text-align:center\">Chỉnh sửa thông tin cá nhân</div></html>  ");
        btnchangeUserInfo.setBorder(null);
        btnchangeUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchangeUserInfoActionPerformed(evt);
            }
        });

        btnChangPass.setBackground(new java.awt.Color(84, 91, 119));
        btnChangPass.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnChangPass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangPass.setText("Đổi mật khẩu");
        btnChangPass.setBorder(null);
        btnChangPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangPassActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(248, 244, 239));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("THÔNG TIN CÁ NHÂN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/name.png"))); // NOI18N
        jLabel8.setText("Họ Tên:");

        tvUserName.setEditable(false);
        tvUserName.setBackground(new java.awt.Color(255, 255, 255));
        tvUserName.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        tvUserName.setForeground(new java.awt.Color(153, 153, 153));
        tvUserName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sex.png"))); // NOI18N
        jLabel3.setText("Giới Tính:");

        tvSex.setEditable(false);
        tvSex.setBackground(new java.awt.Color(255, 255, 255));
        tvSex.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        tvSex.setForeground(new java.awt.Color(153, 153, 153));
        tvSex.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/birthday.png"))); // NOI18N
        jLabel4.setText("Ngày Sinh:");

        tvDOB.setEditable(false);
        tvDOB.setBackground(new java.awt.Color(255, 255, 255));
        tvDOB.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        tvDOB.setForeground(new java.awt.Color(153, 153, 153));
        tvDOB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/location.png"))); // NOI18N
        jLabel5.setText("Địa Chỉ:");

        tvAddress.setEditable(false);
        tvAddress.setBackground(new java.awt.Color(255, 255, 255));
        tvAddress.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        tvAddress.setForeground(new java.awt.Color(153, 153, 153));
        tvAddress.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phone.png"))); // NOI18N
        jLabel6.setText("Số Điện Thoại:");

        tvSDT.setEditable(false);
        tvSDT.setBackground(new java.awt.Color(255, 255, 255));
        tvSDT.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        tvSDT.setForeground(new java.awt.Color(153, 153, 153));
        tvSDT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tvUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(tvSex)
                            .addComponent(tvDOB)
                            .addComponent(tvAddress)
                            .addComponent(tvSDT)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tvUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tvSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tvDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tvAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tvSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnchangeUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnChangPass, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tvAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateAvatar)
                        .addGap(131, 131, 131)
                        .addComponent(btnChangPass, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnchangeUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout tabttTaiKhoanLayout = new javax.swing.GroupLayout(tabttTaiKhoan);
        tabttTaiKhoan.setLayout(tabttTaiKhoanLayout);
        tabttTaiKhoanLayout.setHorizontalGroup(
            tabttTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabttTaiKhoanLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabttTaiKhoanLayout.setVerticalGroup(
            tabttTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabPane.addTab("Thông tin tài khoản", tabttTaiKhoan);

        tabLoaiTB.setBackground(new java.awt.Color(248, 244, 239));

        tbLoaiTB.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        tbLoaiTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Loại", "Tên Loại", "ID Nhân Viên", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLoaiTB.setRowHeight(60);
        tbLoaiTB.setSelectionBackground(new java.awt.Color(0, 51, 153));
        tbLoaiTB.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setViewportView(tbLoaiTB);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel1.setText("Mã loại:");

        tfMaLoai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfMaLoai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel7.setText("Tên loại:");

        tfTenLoai.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfTenLoai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        btnAddLoaiTB.setBackground(new java.awt.Color(68, 119, 206));
        btnAddLoaiTB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAddLoaiTB.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLoaiTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-checkmark-32.png"))); // NOI18N
        btnAddLoaiTB.setText("Xác nhận");
        btnAddLoaiTB.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        btnAddLoaiTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLoaiTBActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel12.setText("THÊM LOẠI THIẾT BỊ MỚI");

        javax.swing.GroupLayout tabLoaiTBLayout = new javax.swing.GroupLayout(tabLoaiTB);
        tabLoaiTB.setLayout(tabLoaiTBLayout);
        tabLoaiTBLayout.setHorizontalGroup(
            tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLoaiTBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabLoaiTBLayout.createSequentialGroup()
                        .addGroup(tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabLoaiTBLayout.createSequentialGroup()
                        .addComponent(btnAddLoaiTB)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabLoaiTBLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        tabLoaiTBLayout.setVerticalGroup(
            tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabLoaiTBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabLoaiTBLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addGroup(tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(tabLoaiTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(btnAddLoaiTB)))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        TabPane.addTab("Loại thiết bị", tabLoaiTB);

        tabDMTB.setBackground(new java.awt.Color(248, 244, 239));
        tabDMTB.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        tabDMTB.setPreferredSize(new java.awt.Dimension(1015, 624));

        tbThietBi.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tbThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Thiết Bị", "ID Loại", "Tên Thiết Bị", "Số lượng", "Đơn giá", "ID Nhân viên", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbThietBi.setRowHeight(55);
        jScrollPane2.setViewportView(tbThietBi);

        tfFindTB.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tfFindTB.setText("Tìm kiếm ...");
        tfFindTB.setToolTipText("");
        tfFindTB.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 3), null));
        tfFindTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfFindTBMouseClicked(evt);
            }
        });
        tfFindTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFindTBActionPerformed(evt);
            }
        });

        btnFindTB.setBackground(new java.awt.Color(153, 204, 255));
        btnFindTB.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnFindTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-32.png"))); // NOI18N
        btnFindTB.setText("Tìm kiếm\n");
        btnFindTB.setBorder(null);
        btnFindTB.setEnabled(false);
        btnFindTB.setOpaque(true);
        btnFindTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindTBActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel13.setText("THÊM THIẾT BỊ MỚI");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setText("ID Thiết bị:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setText("Tên thiết bị:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setText("Số lượng:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel17.setText("Đơn giá:");

        btnAddTB.setBackground(new java.awt.Color(68, 119, 206));
        btnAddTB.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAddTB.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-checkmark-32.png"))); // NOI18N
        btnAddTB.setText("Xác nhận");
        btnAddTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTBActionPerformed(evt);
            }
        });

        tfIDThietBi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfIDThietBi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setText("Loại thiết bị:");

        cbIDLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbIDLoai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tfTenThietBi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfTenThietBi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tfSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfSoLuong.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tfDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfDonGia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        tfDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDonGiaActionPerformed(evt);
            }
        });

        btnImageThietBi.setBackground(new java.awt.Color(153, 204, 255));
        btnImageThietBi.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnImageThietBi.setText("Chọn ảnh:");
        btnImageThietBi.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        btnImageThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageThietBiActionPerformed(evt);
            }
        });

        tfImageThietBi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfImageThietBi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        javax.swing.GroupLayout tabDMTBLayout = new javax.swing.GroupLayout(tabDMTB);
        tabDMTB.setLayout(tabDMTBLayout);
        tabDMTBLayout.setHorizontalGroup(
            tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDMTBLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDMTBLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tfFindTB, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDMTBLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFindTB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
            .addGroup(tabDMTBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(20, 20, 20)
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDMTBLayout.createSequentialGroup()
                        .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(tfIDThietBi)
                            .addComponent(tfDonGia))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImageThietBi)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbIDLoai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfImageThietBi)))
                    .addGroup(tabDMTBLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(tfTenThietBi)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabDMTBLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddTB)
                .addGap(241, 241, 241))
        );
        tabDMTBLayout.setVerticalGroup(
            tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDMTBLayout.createSequentialGroup()
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabDMTBLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tfFindTB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFindTB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImageThietBi)
                        .addComponent(tfImageThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfIDThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cbIDLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(tabDMTBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfTenThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAddTB)
                .addGap(42, 42, 42))
        );

        TabPane.addTab("Danh mục thiết bị", tabDMTB);

        tabHD.setBackground(new java.awt.Color(248, 244, 239));
        tabHD.setToolTipText("");
        tabHD.setName(""); // NOI18N

        btnThemHD.setBackground(new java.awt.Color(68, 119, 206));
        btnThemHD.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnThemHD.setForeground(new java.awt.Color(255, 255, 255));
        btnThemHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice.png"))); // NOI18N
        btnThemHD.setText("Thêm hóa đơn");
        btnThemHD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        tbHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Hóa đơn", "ID Khách hàng", "Ngày mua", "Số lượng", "Thành tiền", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHoaDon.setRowHeight(50);
        jScrollPane3.setViewportView(tbHoaDon);

        javax.swing.GroupLayout tabHDLayout = new javax.swing.GroupLayout(tabHD);
        tabHD.setLayout(tabHDLayout);
        tabHDLayout.setHorizontalGroup(
            tabHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabHDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        tabHDLayout.setVerticalGroup(
            tabHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabHDLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TabPane.addTab("Hóa đơn", tabHD);

        pieChartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelThongKeLayout = new javax.swing.GroupLayout(panelThongKe);
        panelThongKe.setLayout(panelThongKeLayout);
        panelThongKeLayout.setHorizontalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelThongKeLayout.setVerticalGroup(
            panelThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pieChartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabPane.addTab("Thống kê", panelThongKe);

        getContentPane().add(TabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, -33, -1, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTTTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTTaiKhoanActionPerformed
        // TODO add your handling code here:
        TabPane.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnTTTaiKhoanActionPerformed

    private void btnLoaiThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiThietBiActionPerformed
        // TODO add your handling code here:
        TabPane.setSelectedIndex(1);
    }//GEN-LAST:event_btnLoaiThietBiActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        // TODO add your handling code here:
        TabPane.setSelectedIndex(3);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnDMThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMThietBiActionPerformed
        // TODO add your handling code here:
        TabPane.setSelectedIndex(2);
        
    }//GEN-LAST:event_btnDMThietBiActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        new DangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnLoaiThietBi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiThietBi1ActionPerformed
        // TODO add your handling code here:
        TabPane.setSelectedIndex(4);
    }//GEN-LAST:event_btnLoaiThietBi1ActionPerformed

    private void btnDMThietBiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDMThietBiMouseReleased
        // TODO add your handling code here:
        btnDMThietBi.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnDMThietBiMouseReleased

    private void btnUpdateAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateAvatarActionPerformed
        // TODO add your handling code here:
        String filename=filePath();
        ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(tvAvatar.getWidth(),tvAvatar.getHeight(),Image.SCALE_SMOOTH));
        tvAvatar.setIcon(imageIcon);
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="update ltjava_doan.nhanvien set Avatar=? where IDNhanVien=?";
        try
        {
            File image=new File(filename);
            byte[]imageData=Files.readAllBytes(image.toPath());
            ps=con.getConnection().prepareStatement(query);
            ps.setBytes(1,imageData);
            ps.setString(2,IDNV);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }//GEN-LAST:event_btnUpdateAvatarActionPerformed

    private void btnAddLoaiTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLoaiTBActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)tbLoaiTB.getModel();
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        String query="insert into ltjava_doan.loaithietbi values(?,?,?)";
        try
        {
            String tenLoai=String.valueOf(tfTenLoai.getText());
            String maLoai=String.valueOf(tfMaLoai.getText());
            if(maLoai==""||tenLoai=="")
            {
                JOptionPane.showMessageDialog(rootPane, "Mã loại và tên loại không được để trống");
            }
            else
            {
                ps=con.getConnection().prepareStatement(query);
                ps.setString(1, maLoai);
                ps.setString(2,tenLoai);
                ps.setString(3, IDNV);
                ps.executeUpdate();
                Vector v=new Vector();
                v.add(maLoai);
                v.add(tenLoai);
                v.add(IDNV);
                model.addRow(v);
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error"+e);
        }
    }//GEN-LAST:event_btnAddLoaiTBActionPerformed

    private void btnAddTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTBActionPerformed
        // TODO add your handling code here:
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        String query="insert into ltjava_doan.thietbi values (?,?,?,?,?,?,?)";
        try
        {
            String idtb=String.valueOf(tfIDThietBi.getText());
            String tentb=String.valueOf(tfTenThietBi.getText());
            String idloai=String.valueOf(cbIDLoai.getSelectedItem());
            int soluong=Integer.parseInt(tfSoLuong.getText());
            double dongia=Double.parseDouble(tfDonGia.getText());
            ps=con.getConnection().prepareStatement(query);
            ps.setString(1, idtb);
            ps.setString(2,idloai);
            ps.setString(3,tentb);
            ps.setInt(4,soluong);
            ps.setDouble(5,dongia);
            ps.setString(6, IDNV);
            ps.setBytes(7,data);
            ps.executeUpdate();
            DefaultTableModel model=(DefaultTableModel)tbThietBi.getModel();
            Vector v=new Vector();
            v.add(idtb);
            v.add(idloai);
            v.add(tentb);
            v.add(soluong);
            v.add(dongia);
            v.add(IDNV);
            model.addRow(v);
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }//GEN-LAST:event_btnAddTBActionPerformed

    private void tfFindTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFindTBActionPerformed
        // TODO add your handling code here:
        tfFindTB.setText("");
        
    }//GEN-LAST:event_tfFindTBActionPerformed

    private void tfFindTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFindTBMouseClicked
        // TODO add your handling code here:
        tfFindTB.setText("");
        btnFindTB.setEnabled(true);
    }//GEN-LAST:event_tfFindTBMouseClicked

    byte[]data; 
    private void btnImageThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageThietBiActionPerformed
        // TODO add your handling code here:
        String filename=filePath();
        try
        {
            File image=new File(filename);
            data=Files.readAllBytes(image.toPath());
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }//GEN-LAST:event_btnImageThietBiActionPerformed

    private void btnFindTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindTBActionPerformed
        // TODO add your handling code here:
        String query;
        String tffind=tfFindTB.getText();
        if(tffind!="")
        {
            query="select * from ltjava_doan.thietbi where TenThietBi like N'%"+tffind+"%'";
        }
        else 
        {
            query="select * from ltjava_doan.thietbi";
        } 
        
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        DefaultTableModel model=(DefaultTableModel)tbThietBi.getModel();
        model.setRowCount(0);
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            if(rs.next()==false) JOptionPane.showMessageDialog(rootPane, "Không tìm thấy thiết bị bạn cần");
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=0;i<=5;i++)
                {
                    v.add(rs.getString("IDThietBi"));
                    v.add(rs.getString("IDLoai"));
                    v.add(rs.getString("TenThietBi"));
                    v.add(rs.getInt("SoLuong"));
                    v.add(rs.getDouble("DonGia"));
                    v.add(rs.getString("IDNhanVien"));
                }
                model.addRow(v);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }//GEN-LAST:event_btnFindTBActionPerformed

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        // TODO add your handling code here:
        new DanhMucThietBi().setVisible(true);
    }//GEN-LAST:event_btnThemHDActionPerformed

    private void tfDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDonGiaActionPerformed

    private void btnChangPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangPassActionPerformed
        // TODO add your handling code here:
        dialogChangePass.setSize(600, 450);
        dialogChangePass.setLocationRelativeTo(null); //canh dilog đăng nhập ở giữa
        dialogChangePass.setVisible(true);
    }//GEN-LAST:event_btnChangPassActionPerformed

    private void btnConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmPassActionPerformed
        // TODO add your handling code here:
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="update ltjava_doan.nhanvien set MatKhau=? where IDNhanVien=?";
        String oldPass=tfOldPass.getText().toString();
        String newPass=tfNewPass.getText().toString();
        String confirmNewPass=tfConfirmNewPass.getText().toString();
        try
        {
            String findPassword="select * from ltjava_doan.nhanvien where IDNhanVien=?";
            ps=con.getConnection().prepareStatement(findPassword);
            ps.setString(1, IDNV);
            rs=ps.executeQuery();
            if(rs.next())
            {
                if(oldPass.contentEquals(rs.getString("MatKhau"))==false)
                {
                    JOptionPane.showMessageDialog(rootPane, "Mật khẩu cũ không khớp");
                }
                else
                {
                    if(newPass.contentEquals(confirmNewPass))
                    {
                        ps=con.getConnection().prepareStatement(query);
                        ps.setString(1,newPass);
                        ps.setString(2, IDNV);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật mật khẩu thành công");
                        dialogChangePass.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Mật khẩu mới và mật khẩu nhập lại không đúng");
                    }
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }//GEN-LAST:event_btnConfirmPassActionPerformed

    private void btnchangeUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchangeUserInfoActionPerformed
        // TODO add your handling code here:
        dialogChangeInfo.setSize(650, 500);
        dialogChangeInfo.setLocationRelativeTo(null); //canh dilog đăng nhập ở giữa
        dialogChangeInfo.setVisible(true);
    }//GEN-LAST:event_btnchangeUserInfoActionPerformed

    private void btnConfirmChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmChangeInfoActionPerformed
        // TODO add your handling code here:
        String sex="";
        if(btnNam.isSelected())
        {
            sex="Nam";
        }
        if(btnNu.isSelected())
        {
            sex="Nữ";
        }
        if(tfChangeUserName.getText().contentEquals("")||sex.contentEquals("")||tfChangeDIaChi.getText().contentEquals("")||tfChangeSDT.getText().contentEquals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Không được để trống các trường thông tin");
        }
        else
        {
            MyConnection con=new MyConnection();
        PreparedStatement ps;
        String query="update ltjava_doan.nhanvien set HoTen=?, GioiTinh=?, DiaChi=?, SDT=? where IDNhanVien=?";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            ps.setString(1, tfChangeUserName.getText());
            ps.setString(2, sex);
            ps.setString(3, tfChangeDIaChi.getText());
            ps.setString(4,tfChangeSDT.getText());
            ps.setString(5, IDNV);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin cá nhân thành công");
            dialogChangeInfo.dispose();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
        }
        
    }//GEN-LAST:event_btnConfirmChangeInfoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }
    
    public void showLoaiThietBi()//Trang LoaiThietBi
    {
        PreparedStatement ps;
        ResultSet rs;
        MyConnection con=new MyConnection();
        String query="select * from ltjava_doan.loaithietbi";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            java.sql.ResultSetMetaData meta=rs.getMetaData();
            int numCol=meta.getColumnCount();
            DefaultTableModel d=(DefaultTableModel) tbLoaiTB.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=0;i<=numCol;i++)
                {
                    v.add(rs.getString("IDLoai"));
                    v.add(rs.getString("TenLoai"));
                    v.add(rs.getString("IDNhanVien"));
                }
                d.addRow(v);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error"+e);
        }
        TableActionEvent event=new TableActionEvent(){
            @Override
            //Cập nhật loại thiết bị
            public void onUpdate(int row) {
                if(tbLoaiTB.isEditing())
                {
                    tbLoaiTB.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model=(DefaultTableModel) tbLoaiTB.getModel();
                MyConnection con=new MyConnection();
                PreparedStatement ps;
                String query="update ltjava_doan.loaithietbi set TenLoai=? where IDLoai=?";
                try{
                    if(model.getValueAt(row, 1).toString()=="")
                    {
                        JOptionPane.showMessageDialog(rootPane, "Không được để trống tên loại");
                    }
                    else
                    {
                        ps=con.getConnection().prepareStatement(query);
                        ps.setString(1,model.getValueAt(row, 1).toString());
                        ps.setString(2, model.getValueAt(row, 0).toString());
                        ps.executeUpdate();
                        model.setValueAt(IDNV, row, 2);
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error"+e);
                }
            }
            //Xóa loại thiết bị
            @Override
            public void onDelete(int row) {
                if(tbLoaiTB.isEditing())
                {
                    tbLoaiTB.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model=(DefaultTableModel)tbLoaiTB.getModel();
                MyConnection con=new MyConnection();
                PreparedStatement ps;
                ResultSet rs;
                String query="delete from ltjava_doan.loaithietbi where IDLoai=?";
                try
                {
                    ps=con.getConnection().prepareStatement(query);
                    ps.setString(1, model.getValueAt(row, 0).toString());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error"+e);
                }
                model.removeRow(row);
            }
            
        };
        tbLoaiTB.getColumnModel().getColumn(3).setCellRenderer(new TableActionCellRender());
        tbLoaiTB.getColumnModel().getColumn(3).setCellEditor(new TableActionCellEditor(event));
    }
    
    public void showHoaDon()
    {
        PreparedStatement ps;
        ResultSet rs;
        MyConnection con=new MyConnection();
        String query="select * from ltjava_doan.hoadon";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            java.sql.ResultSetMetaData meta=rs.getMetaData();
            int numCol=meta.getColumnCount();
            DefaultTableModel d=(DefaultTableModel) tbHoaDon.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=0;i<=numCol;i++)
                {
                    v.add(rs.getString("IDHoaDon"));
                    if(rs.getString("IDKhachHang")==null) v.add("Khách vãng lai");
                    else v.add(rs.getString("IDKhachHang"));
                    v.add(rs.getDate("NgayMua").toString());
                    v.add(rs.getInt("TongSoLuongMua"));
                    v.add(rs.getDouble("TongTien"));
                }
                d.addRow(v);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
        viewEvent event=new viewEvent(){
            //xem chi tiết hóa đơn
            public void onView(int row)
            {
                dialogshowCTHD.setSize(802, 547);
                dialogshowCTHD.setLocationRelativeTo(null); //canh dilog đăng nhập ở giữa
                dialogshowCTHD.setVisible(true);
                DefaultTableModel model=(DefaultTableModel)tbHoaDon.getModel();
                String idhd=String.valueOf(model.getValueAt(row, 0).toString());
                showCTHD(idhd);
            }
        };
        tbHoaDon.getColumnModel().getColumn(5).setCellRenderer(new viewCellRender());
        tbHoaDon.getColumnModel().getColumn(5).setCellEditor(new viewActionCellEditor(event));
    }
    
    public void showThietBi()
    {
        updateComboBoxTB();
        PreparedStatement ps;
        ResultSet rs;
        MyConnection con=new MyConnection();
        String query="select * from ltjava_doan.thietbi";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            java.sql.ResultSetMetaData meta=rs.getMetaData();
            int numCol=meta.getColumnCount();
            DefaultTableModel d=(DefaultTableModel) tbThietBi.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=0;i<=numCol;i++)
                {
                    v.add(rs.getString("IDThietBi"));
                    v.add(rs.getString("IDLoai"));
                    v.add(rs.getString("TenThietBi"));
                    v.add(rs.getInt("SoLuong"));
                    v.add(rs.getDouble("DonGia"));
                    v.add(rs.getString("IDNhanVien"));
                }
                d.addRow(v);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
        
        TableActionEvent event=new TableActionEvent(){
            @Override
            //Cập nhật loại thiết bị
            public void onUpdate(int row) {
                if(tbThietBi.isEditing())
                {
                    tbThietBi.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model=(DefaultTableModel) tbThietBi.getModel();
                MyConnection con=new MyConnection();
                PreparedStatement ps;
                String query="update ltjava_doan.thietbi set TenThietBi=?, SoLuong=?, DonGia=?, IDNhanVien=? where IDThietBi=?";
                try{
                    if(model.getValueAt(row, 2).toString()==""||model.getValueAt(row, 3)==null||model.getValueAt(row, 4)==null)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Không được để trống tên thiết bị, số lượng và đơn giá");
                    }
                    else
                    {
                        ps=con.getConnection().prepareStatement(query);
                        ps.setString(1,String.valueOf(model.getValueAt(row, 2)));
                        ps.setInt(2, Integer.parseInt(model.getValueAt(row, 3).toString()));
                        ps.setDouble(3,Double.parseDouble(model.getValueAt(row, 4).toString()));
                        ps.setString(5,String.valueOf(model.getValueAt(row, 0)));
                        ps.setString(4, IDNV);
                        ps.executeUpdate();
                        model.setValueAt(IDNV, row, 5);
                        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error"+e);
                }
            }
            //Xóa loại thiết bị
            @Override
            public void onDelete(int row) {
                if(tbLoaiTB.isEditing())
                {
                    tbLoaiTB.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model=(DefaultTableModel)tbThietBi.getModel();
                MyConnection con=new MyConnection();
                PreparedStatement ps;
                ResultSet rs;
                String query="delete from ltjava_doan.thietbi where IDThietBi=?";
                try
                {
                    ps=con.getConnection().prepareStatement(query);
                    ps.setString(1, model.getValueAt(row, 0).toString());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error"+e);
                }
                model.removeRow(row);
            }
            
        };
        tbThietBi.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
        tbThietBi.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor(event));
    }
    public void showCTHD(String idHD)
    {
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="select IDHoaDon, TenThietBi, SoLuongMua, ThanhTien from ltjava_doan.chitiethoadon, ltjava_doan.thietbi where IDHoaDon =? and thietbi.IDThietBi=chitiethoadon.IDThietBi";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            ps.setString(1,idHD);
            rs=ps.executeQuery();
            java.sql.ResultSetMetaData meta=rs.getMetaData();
            int numCol=meta.getColumnCount();
            DefaultTableModel d=(DefaultTableModel) tbCTHD.getModel();
            d.setRowCount(0);
            while(rs.next())
            {
                Vector v=new Vector();
                for(int i=0;i<=numCol;i++)
                {
                    v.add(rs.getString("IDHoaDon"));
                    v.add(rs.getString("TenThietBi"));
                    v.add(rs.getInt("SoLuongMua"));
                    v.add(rs.getDouble("ThanhTien"));
                }
                d.addRow(v);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }
    public void updateComboBoxTB()
    {
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="select * from ltjava_doan.loaithietbi";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next())
            {
                cbIDLoai.addItem(rs.getString("IDLoai"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }
    
    public void showAvatar()
    {
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="select Avatar from ltjava_doan.nhanvien where IDNhanVien=?";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            ps.setString(1,IDNV);
            rs=ps.executeQuery();
            if(rs.next())
            {
                byte[]imageData=rs.getBytes("Avatar");
                if(imageData!=null)
                {
                    InputStream in=new ByteArrayInputStream(imageData);
                    BufferedImage image=ImageIO.read(in);
                    tvAvatar.setIcon(new ImageIcon(image));
                }
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,"Error"+e);
        }
    }
    
    public String filePath()
    {
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        return filename;
    }
    
    public void sumOfSP()
    {
        String idsp;
        String tensp;
        MyConnection con=new MyConnection();
        PreparedStatement ps;
        ResultSet rs;
        String query="select * from ltjava_doan.thietbi";
        try
        {
            ps=con.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next())
            {
                ResultSet rs1;
                PreparedStatement ps1;
                idsp=rs.getString("IDThietBi");
                tensp=rs.getString("TenThietBi");
                int sl=0;
                String query1="select sum(SoLuongMua) as tongsl from ltjava_doan.chitiethoadon where IDThietBi=?";
                ps1=con.getConnection().prepareStatement(query1);
                ps1.setString(1,idsp);
                rs1=ps1.executeQuery();
                if(rs1.next())
                {
                    sl=rs1.getInt("tongsl");
                    if(sl>0)
                    {
                        BanHD banhd=new BanHD();
                        banhd.setIdsp(tensp+": "+sl);
                        banhd.setSlBan(sl);
                        listSP.add(banhd);
                    }
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error"+e);
        }
    }  
    
    public void showPieChart()
    {
        sumOfSP();
        pieDataSet=new DefaultPieDataset();
        for(BanHD item: listSP)
        {
            pieDataSet.setValue(item.getIdsp(),item.getSlBan());
        }
        /*pieDataSet.setValue("hi",10);
        pieDataSet.setValue("hello",12);
        pieDataSet.setValue("what",10);*/
        pieChart=ChartFactory.createPieChart("Các sản phẩm bán nhiều nhất", pieDataSet,true, true, false);
        piePlot=(PiePlot)pieChart.getPlot();
        chartPanel=new ChartPanel(pieChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(800,600));
        pieChartPanel.removeAll();
        pieChartPanel.add(chartPanel);
        chartPanel.validate();
    }
    
    private DefaultPieDataset pieDataSet;
    private JFreeChart pieChart;
    private PiePlot piePlot;
    private ChartPanel chartPanel;
    public ArrayList<BanHD> listSP=new ArrayList<>();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JButton btnAddLoaiTB;
    private javax.swing.JButton btnAddTB;
    private javax.swing.JButton btnChangPass;
    private javax.swing.JButton btnConfirmChangeInfo;
    private javax.swing.JButton btnConfirmPass;
    private javax.swing.JButton btnDMThietBi;
    private javax.swing.JButton btnFindTB;
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnImageThietBi;
    private javax.swing.JButton btnLoaiThietBi;
    private javax.swing.JButton btnLoaiThietBi1;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JRadioButton btnNam;
    private javax.swing.JRadioButton btnNu;
    private javax.swing.JButton btnTTTaiKhoan;
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnUpdateAvatar;
    private javax.swing.JButton btnchangeUserInfo;
    private javax.swing.JComboBox<String> cbIDLoai;
    private javax.swing.JDialog dialogChangeInfo;
    private javax.swing.JDialog dialogChangePass;
    private javax.swing.JDialog dialogshowCTHD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelThongKe;
    private javax.swing.JPanel pieChartPanel;
    private javax.swing.JPanel tabDMTB;
    private javax.swing.JPanel tabHD;
    private javax.swing.JPanel tabLoaiTB;
    private javax.swing.JPanel tabttTaiKhoan;
    private javax.swing.JTable tbCTHD;
    private javax.swing.JTable tbHoaDon;
    private javax.swing.JTable tbLoaiTB;
    private javax.swing.JTable tbThietBi;
    private javax.swing.JTextField tfChangeDIaChi;
    private javax.swing.JTextField tfChangeSDT;
    private javax.swing.JTextField tfChangeUserName;
    private javax.swing.JPasswordField tfConfirmNewPass;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfFindTB;
    private javax.swing.JTextField tfIDThietBi;
    private javax.swing.JTextField tfImageThietBi;
    private javax.swing.JTextField tfMaLoai;
    private javax.swing.JPasswordField tfNewPass;
    private javax.swing.JPasswordField tfOldPass;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenLoai;
    private javax.swing.JTextField tfTenThietBi;
    private javax.swing.JTextField tvAddress;
    private javax.swing.JLabel tvAvatar;
    private javax.swing.JTextField tvDOB;
    private javax.swing.JTextField tvSDT;
    private javax.swing.JTextField tvSex;
    private javax.swing.JTextField tvUserName;
    // End of variables declaration//GEN-END:variables
}

