/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Component;

import java.awt.BorderLayout;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GioHangView extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    private JTable table;
    /**
     * Creates new form GioHangView
     */
    public GioHangView() {
        String[] columnNames={"STT","Tên sản phẩm","Số lượng","Giá"};
        tableModel=new DefaultTableModel(columnNames,0);
        table= new JTable(tableModel);
        
        JScrollPane scrollPane=new JScrollPane(table);
        setLayout(new BorderLayout());
        add(scrollPane,BorderLayout.CENTER);
        
        //
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
//        addGioHang("Sản phẩm 1", 10, 100.0);
//        addGioHang("Sản phẩm 2", 5, 50.0);
//        addGioHang("Sản phẩm 3", 3, 30.0);
//        addGioHang("Sản phẩm 4", 2, 20.0);
//        addGioHang("Sản phẩm 5", 8, 80.0);
    }
    public void addGioHang(String tenSP,int soLuong,double gia){
        Object[] rowData={table.getRowCount()+1,tenSP,soLuong,gia};
        tableModel.addRow(rowData);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
